name: Development Workflow

on:
  push:
    branches:
      - approved

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get latest tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: /web
          releases-only: false
        id: repo
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/web:${{ steps.repo.outputs.tag }}-app
            ${{ secrets.DOCKERHUB_USERNAME }}/web:latest-app
