name: Development Workflow

on:
  push:
    branches:
      - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tag:
    name: Tag Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm install

      - name: Git config email
        run: git config --global user.email "dev@.com"

      - name: Git config name
        run: git config --global user.name ""

      - name: Create Release Pull Request
        run: npm run tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  docker:
    name: Docker Build
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get latest tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: /web
          releases-only: false
        id: repo
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/web:${{ steps.repo.outputs.tag }}-dev
            ${{ secrets.DOCKERHUB_USERNAME }}/web:latest-dev
